name: lint
on: push
jobs:
  randomize:
    runs-on: ubuntu-latest
    concurrency:
      group: staging_environment2
      cancel-in-progress: false
    steps:
      - name: debloat
        uses: actions/checkout@v4
      - name: Maximize build disk space
        shell: bash
        run: |
          set -euo pipefail

          BUILD_MOUNT_PATH="${{ inputs.build-mount-path }}"
          if [[ -z "${BUILD_MOUNT_PATH}" ]]; then
            BUILD_MOUNT_PATH="${GITHUB_WORKSPACE}"
          fi

          echo "Arguments:"
          echo
          echo -n "  Removing:     "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            echo -n "dotnet "
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            echo -n "android "
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            echo -n "haskell "
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            echo -n "codeql "
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            echo -n "docker "
          fi
          echo

          # store owner of $GITHUB_WORKSPACE in case the action deletes it
          WORKSPACE_OWNER="$(stat -c '%U:%G' "${GITHUB_WORKSPACE}")"

          # ensure mount path exists before the action
          sudo mkdir -p "${BUILD_MOUNT_PATH}"
          sudo find "${BUILD_MOUNT_PATH}" -maxdepth 0 ! -empty -exec echo 'WARNING: directory [{}] is not empty, data loss might occur. Content:' \; -exec ls -al "{}" \;

          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            sudo rm -rf /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            sudo rm -rf /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            sudo rm -rf /opt/ghc
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            sudo rm -rf /opt/hostedtoolcache/CodeQL
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            sudo docker image prune --all --force
          fi
          echo "... done"
      - name: Disk space report after modification
        shell: bash
        run: |
          echo "Memory and swap:"
          sudo free -h
          echo
          sudo swapon --show
          echo

          echo "Available storage:"
          sudo df -h
